"""
Helper class that generates a TeX / pdf file from the sp_{2n} pipeline results for enhanced visibility of the raw data.
Uses existing results if possible.
If no results exist for a certain n, it will run the verification pipeline.
"""

from pathlib import Path
import pandas as pd
from pylatex import Document, NoEscape, NewPage, Package, Section

from core.sp2n_pipeline import sp2n_pipeline
from utils.partitions import Partition
from utils.formatting import format_partition, format_number
from utils.versioning import get_latex_file_name, get_results_file_name
from utils.styles import color, console, bold, status_as_text

TABLE_TEMPLATE_START = lambda n: (
    "\n"
    "    \\begin{center}\n"
    "    \\label{table:sp_" + str(2 * n) + "}\n"
    "    \\begin{longtable}{||c|c|c|c|c|c|c||}\n"
    "    \\hline\n"
    "    Partition \\textbf{d}\n"
    "    &Peaks\n"
    "    &$\\operatorname{argmax}\\, r_i(\\textbf{d})$\n"
    "    &$r(\\textbf{d})$\n"
    "    &$\\delta(\\textbf{d})$\n"
    "    &$r(\\textbf{d}) \\cdot \\delta(\\textbf{d})$\n"
    "    &Remarks\n"
    "    \\\\ [0.3ex] \\hline\\endhead\n"
)
TABLE_TEMPLATE_END = (
    "    \\end{longtable}\n"
    "    \\end{center}\n"
)
TABLE_ROW_SEPARATOR = " \\\\ \\hline \n"



def generate_pdf(min_n: int, max_n: int) -> None:
    """Generate a multi-table ``.pdf`` file for sp_{2*min_n} through sp_{2*max_n}.
    Creates a raw ``.tex`` version first and then compiles it.

    Parameters
    ----------
    min_n:
        The smallest rank parameter to include.
    max_n:
        The largest rank parameter to include (inclusive).
    """
    file_name = generate_tex_doc(min_n, max_n)

    # TODO: COMPILE
    
    console.print(bold(color(f".pdf file saved as {file_name}.pdf", "green")))

    return file_name


def generate_tex_doc(min_n: int, max_n: int) -> None:
    """Generate a multi-table ``.tex`` file for sp_{2*min_n} through sp_{2*max_n}.

    Parameters
    ----------
    min_n:
        The smallest rank parameter to include.
    max_n:
        The largest rank parameter to include (inclusive).
    """
    console.print("Collecting results.")
    all_results = collect_results(min_n, max_n)

    console.print("Generating LaTeX document.")
    doc = _get_base_of_tex_doc()

    for n in range(min_n, max_n + 1):
        sp2n_data = all_results[n]
        table = generate_tex_table(sp2n_data, n)
        _add_table_to_doc(doc, table, n)

    file_name = get_latex_file_name(min_n, max_n)
    doc.generate_tex(file_name)
    console.print(bold(color(f".tex file saved as {file_name}.tex", "green")))

    return file_name


def generate_tex_table(partition_data: pd.DataFrame, n: int) -> str:
    """Generate a LaTeX ``longtable`` string for the sp_{2n} orbit data.

    Parameters
    ----------
    partition_data:
        A DataFrame containing the partition data for the sp_{2n} algebra.
    n:
        The rank of the ambient Lie algebra sp_{2n}.

    Returns
    -------
    str
        A self-contained LaTeX snippet containing a ``longtable`` wrapped in a ``center`` environment.
    """    
    table_rows: list[str] = []

    for record in partition_data.to_dict(orient="records"):
        p: Partition = dict(record["Partition"])
        is_regular = p == {2 * n: 1}
        is_trivial = p == {1: 2 * n}

        if not is_trivial:
            peaks_str = ",".join(str(idx) for idx in record["Peaks"])
        if not is_regular:
            max_rate_idx_str = ",".join(str(idx) for idx in record["Global Rate Indices"])
            r: float = record["Rate"]

        delta: int = record["Delta"]
        label: str = record["Label"] if record["Label"] != "" else "-"

        table_rows.append(
            " & ".join([
                f"${format_partition(p)}$",
                f"${peaks_str}$" if not is_trivial else "NA",
                f"${max_rate_idx_str}$" if not is_regular else "NA",
                f"${format_number(r)}$" if not is_regular else "$\\infty$",
                f"${format_number(delta)}$",
                f"${format_number(r * delta)}$" if not is_regular else "NA",
                label
            ])
        )

    return (
        TABLE_TEMPLATE_START(n)
        + TABLE_ROW_SEPARATOR.join(table_rows)
        + TABLE_ROW_SEPARATOR
        + TABLE_TEMPLATE_END
    )


def collect_results(min_n: int, max_n: int) -> dict[int, pd.DataFrame]:
    """
    Collects the existing results for all algebras $sp_{2n}$ with n between min_n and max_n.
    Missing computation outcome files are generated and saved for completion of the result.

    Returns a dictionary with keys = range(min_n, max_n+1),
    whose value at a specific 'n' is the result dataframe of $sp_{2n}$,
    as generated by :func:`core.sp2n_pipeline.sp2n_pipeline`.
    """
    data = {}

    for n in range(min_n, max_n+1):
        results_path = Path(get_results_file_name(n=n))

        # If the results file for n does not exist or is empty, run the pipeline to generate it.
        if (not results_path.is_file()) or results_path.stat().st_size == 0:
            print(f"Results file for sp_{2*n} not found or empty. Running pipeline to generate it.")
            data[n] = sp2n_pipeline(n, results_path).run()
        else:
            data[n] = pd.read_csv(results_path)

    return data


def _get_base_of_tex_doc() -> Document:
    """Return a base LaTeX document with the required packages and settings."""
    doc = Document(documentclass="article", document_options=["a4paper"])
    doc.packages.append(Package("longtable"))
    doc.packages.append(Package("geometry", options=["margin=1in", "footskip=1in"]))
    doc.packages.append(Package("amsmath"))
    doc.packages.append(Package("amsfonts"))

    return doc


def _add_table_to_doc(doc: Document, table_tex: str, n: int) -> None:
    """Add a LaTeX table to the document with a section header for sp_{2n}."""
    with doc.create(
            Section(NoEscape(r"$\mathfrak{sp}_{" + str(2 * n) + r"}$"), label=False)
        ):
            doc.append(NoEscape(table_tex))
            doc.append(NewPage())
